### ISSUE TITLE
how to deploy node in this examples into thingsboard

### ISSUE THREAD

**Issue by ten2net** [thingsboard/rule-node-examples#1]
Defined configuration directive 'tbEnrichmentNodeSumIntoMetadataConfig' is not available

**Comment by ShvaykaD** [comment]
HI, @ten2net  we prepare an article on our website page that will be described how to deploy it to ThingsBoard.
I'll let you know as soon as it will be done.

**Comment by ShvaykaD** [comment]
Hi, @ten2net  refer to the following link to view the article mentioned above: https://thingsboard.io/docs/user-guide/contribution/rule-node-development/

**Comment by esonhon** [comment]
I encountered same error in tb2.3.1

**Comment by Anthony1957** [comment]
Hi Team,
I tried to add custom nodes following your article and was success. But I ran into problems when I refactored the package names to my own package names. I Have few points to be clarified
1. Do we have to use package names org.thingsboard.rule.engine.node.Xxxxx always
2. If we implement FILTER type node it always have to be in org.thingsboard.rule.engine.node.filter package
3. I also got configuration directive 'tbMyTestNodeConfig' is not available when i tried to implement a new node following Check-key node, what could be the reason
Pls help, thanks

**Comment by smatvienko-tb** [comment]
Hey! It's better to follow the examples in this project. 
1. The package name recommended is `org.thingsboard.rule.engine.node.xxxxx`
2. The node type is described inside annotation `@RuleNode` but in the package name itself.
3. I believe in the latest version it all work fine
