### ISSUE TITLE
getPeContext() doesn't seem available

### ISSUE THREAD

**Issue by skewty** [thingsboard/rule-node-examples#13]
I need `org.thingsboard.server.dao.group.EntityGroupService` for a node I am trying to write and discovered that it is oddly missing from `TbContext` which has the others services.

Trying to just bring it into my class like:
```java
    protected EntityGroupService getEntityGroupService()
```
is also a problem because the compiler thinks `group.EntityGroupService` doesn't exist when I `import org.thingsboard.server.dao.group.EntityGroupService;`

Thinking it could be a PE only thing I set my `pom.xml` to have
`<thingsboard.version>3.4.0PE</thingsboard.version>` and did a 
`mvn clean install` again but that didn't help.

Any ideas how I can get `EntityGroupService` or if it could be added into `TbContext` for a future release?

**Comment by smatvienko-tb** [comment]
There are two contexts: TbContext - for community edition and TbPeContext - for a professional edition that contains `EntityGroupService getEntityGroupService()`

**Comment by skewty** [comment]
![image](https://user-images.githubusercontent.com/9087223/183683242-6af9bfc1-ce0b-4a9c-8333-b4e0ad66e468.png)

**Comment by skewty** [comment]
Is it just a linting issue that I will have to ignore?

**Comment by smatvienko-tb** [comment]
I made an example for you. It works like a charm.
https://github.com/smatvienko-tb/rule-node-examples/pull/1/files

Probably, reload maven project will help IntelliJ Idea to refresh classes
![image](https://user-images.githubusercontent.com/79898499/183687903-8e88260f-9934-4afd-b71f-32d9028d5248.png)

**Comment by skewty** [comment]
Reloading IntelliJ didn't help but a Build: Sync refresh did.

PS: massive thanks for the help today. Can I send you some money somehow to buy you lunch or something to show my appreciation?

**Comment by smatvienko-tb** [comment]
> Reloading IntelliJ didn't help but a Build: Sync refresh did.
> 
> PS: massive thanks for the help today. Can I send you some money somehow to buy you lunch or something to show my appreciation?

A single star on the [Thingsboard](https://github.com/thingsboard/thingsboard) will be more than enough! Have a good day!
