### ISSUE TITLE
Is there any option to hot reload custom rule nodes (cluster deployment) to be applied?

### ISSUE THREAD

**Issue by alexcorvis84** [thingsboard/rule-node-examples#17]
Hi @smatvienko-tb,

Could you please check [this question](https://github.com/thingsboard/thingsboard/issues/8279#issuecomment-1552710339)?

It's similar to one that was [previously submitted](https://github.com/thingsboard/rule-node-examples/issues/7), but in this case I'm using Thingsboard deployed in **cluster** with **docker-compose** setup.

I'm wondering if there's any possibility to reload **JUST** some of the microservices in order to apply changes. In that case, which ones (from **docker-compose ps -a** output attached in the related issue link) should I restart?

Also I've noticed that I could check that the custom nodes appears (restarting all the services), **BUT** another colleague tried to login and use them and **he can't see the custom nodes**. I've just uploaded the custom node ***.jar** files to one of the services (**tb-core1** and _/usr/share/thingsboard/extensions_ location). 

I'm wondering if it can be the reason why my colleague does not see it? 
Does each **tb-core** replicated service **need to contain** the **custom nodes files**? In this case, is there any possibility to configure that all of them share the same volume where the custom nodes could be located making them available for the replicas?

Hope you can help me to address above questions.

Many thanks in advance and don't hesitate to ask me if you need more details ;)

**Comment by smatvienko-tb** [comment]
Hi @alexcorvis84 

> Hi @smatvienko-tb,
> 
> Could you please check [this question](https://github.com/thingsboard/thingsboard/issues/8279#issuecomment-1552710339)?
> 
> It's similar to one that was [previously submitted](https://github.com/thingsboard/rule-node-examples/issues/7), but in this case I'm using Thingsboard deployed in **cluster** with **docker-compose** setup.
> 
> I'm wondering if there's any possibility to reload **JUST** some of the microservices in order to apply changes. In that case, which ones (from **docker-compose ps -a** output attached in the related issue link) should I restart?

To apply custom rule nodes for the `rule-engine` only, you have to update and restart all replicas `tb-rule-engine`.

To apply custom rule nodes for the _user interface_, you need to update and restart all replicas `tb-core`.

Other microservices do not require a restart. You can do a rolling update (one by one) without downtime at all.

Every replica has to have exactly the same custom rule nodes jar.

> 
> Also I've noticed that I could check that the custom nodes appears (restarting all the services), **BUT** another colleague tried to login and use them and **he can't see the custom nodes**. I've just uploaded the custom node ***.jar** files to one of the services (**tb-core1** and _/usr/share/thingsboard/extensions_ location).

Applying changes for 1 of 2 nodes have only sense for the **A/B testing**. In that case, you must directly connect to `tb-core-1` to see the changes.

> 
> I'm wondering if it can be the reason why my colleague does not see it? Does each **tb-core** replicated service **need to contain** the **custom nodes files**? In this case, is there any possibility to configure that all of them share the same volume where the custom nodes could be located making them available for the replicas?

Another colleague probably connected to the `tb-core-0` by the load balancer and see the other reality.

> 
> Hope you can help me to address above questions.
> 
> Many thanks in advance and don't hesitate to ask me if you need more details ;)

Have a good day!

**Comment by alexcorvis84** [comment]
Hi @smatvienko-tb 

Got it! Thank you so much for your support!

Have a nice day too ;)
