### ISSUE TITLE
Documentation references invalid GIT branch

### ISSUE THREAD

**Issue by skewty** [thingsboard/rule-node-examples#24]
https://thingsboard.io/docs/user-guide/contribution/rule-node-development/
instructs users to checkout 3.6 branch but it doesn't exist.

How do I develop for 3.6?  Shouldn't there also be a 3.6.1 branch?

**Comment by skewty** [comment]
For others who come here, I tried checking out 3.5 branch and changing the value in `pom.xml` from `3.5.0` to `3.6.1` (files exist [here](https://repo.thingsboard.io/artifactory/libs-release-public/org/thingsboard/rule-engine/rule-engine-api/3.6.1/)) and running `mvn clean install` but got this error

```
class lombok.javac.apt.LombokProcessor (in unnamed module @0x269c7104) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x269c7104
```
as seen below

![image](https://github.com/thingsboard/rule-node-examples/assets/9087223/9bbf5e66-7dd5-4c64-bf8c-50d02799a96e)

I tried with jre-17-openjdk (version 17.0.9). Perhaps there is a specific Java version requirement not mentioned anywhere in the `README.md`?

**Comment by smatvienko-tb** [comment]
Hi, @skewty !
The quick solution for you is to use Java 11 for 3.6.X ThingsBoard versions 
To build custom rule nodes for your ThingsBoard version, please update version in pom.xml with exact version you are using at this moment. There are no breaking changes between 3.5 and 3.6 rule nodes as far as I remember and you are likely will archive your goals with less effort.
```
<thingsboard.version>3.5.0</thingsboard.version>
```

**Comment by skewty** [comment]
Just changed to java 11 and used 3.6.0 (the version I have running in a local Docker I develop against).

Now it would seem `org.thingsboard.rule.engine.api.TbRelationTypes` enum is missing from non PE version if I had to guess? That seems wrong to me.

![image](https://github.com/thingsboard/rule-node-examples/assets/9087223/d9639237-7b1c-4bac-a299-5d0b89f0a84d)

**Comment by smatvienko-tb** [comment]
@skewty please, check my PR with 3.6.0 upgrade. 
https://github.com/thingsboard/rule-node-examples/pull/25/files

You can copy changes in your project

**Comment by skewty** [comment]
@smatvienko-tb can I buy you a coffee or something?  Any easy ways to send small money to 🇺🇦 ?

**Comment by smatvienko-tb** [comment]
> @smatvienko-tb can I buy you a coffee or something? Any easy ways to send small money to 🇺🇦 ?

@skewty TY! I'm ok. Enjoy the ride with your ThingsBoard!

[Come Back Alive Foundation](https://savelife.in.ua/en/donate-en/#donate-army-card-once)
![image](https://github.com/thingsboard/rule-node-examples/assets/79898499/9c8a9fa4-143b-4ca3-a20c-83ffae446673)
