### ISSUE TITLE
Custom Rule Node: Unable to Inject Configuration from thingsboard.yml

### ISSUE THREAD

**Issue by avj-vaibhav** [thingsboard/rule-node-examples#29]
## Description
I am creating a Custom Rule Node that requires configuration parameters from `thingsboard.yml`, separate from the standard `TbNodeConfiguration`. These parameters are used to initialize variables in the Custom Rule Node. 

## Issue
Tried two approaches:

1. Created a `@Configuration` class inside the `rule-engine-components` module (within the custom node folder).
2. Created a `CustomNodeConfig` interface in `rule-engine-api` and a `@Component` for the same in `org.thingsboard.server.config` (in application module).

In both cases, the configuration bean is not being injected into the Custom Rule Node.

## Expected
The configuration defined in thingsboard.yml should be injected into the Custom Rule Node during initialization.

## Environment
ThingsBoard version: 3.5.1

**Comment by smatvienko-tb** [comment]
Hi!
The Spring component and configuration do not initialize at custom rule node injection.

You can try to access your values through the context containing numerous existing components.

Another more straightforward way is to read the ENV variable without Spring using vanilla Java.

```
String myEnvVar = System.getenv("MY_ENV_VAR");
```
