### ISSUE TITLE
error in custom node example compilation

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/rule-node-examples#5]
Hi,

 I have  managed to run maven install   for  version 3.2.0PE following the instructions in https://thingsboard.io/docs/user-guide/contribution/rule-node-development/#step-1-download-and-build-sample-project 

BUT code there is compilation issue in all 3 rule nodes  related to configuration setKey()/ getKey() functions. 
e.g. filter node 
https://github.com/thingsboard/rule-node-examples/blob/master/src/main/java/org/thingsboard/rule/engine/node/filter/TbKeyFilterNode.java#L53

The method getKey() is undefined for the type TbKeyFilterNodeConfiguration

https://github.com/thingsboard/rule-node-examples/blob/master/src/main/java/org/thingsboard/rule/engine/node/filter/TbKeyFilterNodeConfiguration.java#L29

The method setKey(null) is undefined for the type TbKeyFilterNodeConfiguration

Am I missing something?  

Thanks in advance for your responce

**Comment by SaifulAlam93** [comment]
I am facing the same issue.

**Comment by swfh22** [comment]
I believe this has to do with the lombok library, in-case anyone else needs the info.

**Comment by smatvienko-tb** [comment]
Please, check the latest master. There are great improvements.
