### ISSUE TITLE
Hot reload custom rule node jar

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/rule-node-examples#7]
Is it possible to hot reload custom rule node jar in `/usr/share/thingsboard/extensions` without restarting thingsboard? Thanks.

**Comment by smatvienko-tb** [comment]
Hey! Unfortunately, it is not possible. Init process happens just once. And it may take a lot of effort to make it without restart. Is it worth it?

Here is some experience from production:
We build docker images each time when we need to deploy the new extensions. For the Kubernetes cluster, it is not a problem at all to use rolling updates. Cluster not going down at all.
The docker images guaranteed that you are running on a proper set of ThingsBoard and extensions.
To simplify development - we do unit tests (see examples in this project) and deploy minor release to the stage environment
