### ISSUE TITLE
Recreate PE Scheduler as a custom rule node

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/rule-node-examples#8]
Is it possible to recreate [PE Scheduler](https://thingsboard.io/docs/pe/user-guide/scheduler/) as a custom rule node in CE? 

Was thinking something like this as a separate rule chain, disjoint from any other rule chains.
**The Scheduler node is a custom rule node**
![image](https://user-images.githubusercontent.com/58241952/148321452-02bb28cf-c984-4f21-a87f-7ba849e7eaef.png)

Any pointer is appreciated!

**Comment by smatvienko-tb** [comment]
Hey! 
You can generate messages with a fixed interval infinitely. Let's say, each minute.
Then you can develop a custom rule node that makes output `True` when action is needed and `False` when action is not needed
